### ISSUE TITLE
Harcoded Icons

### ISSUE THREAD

**Issue by cesasol** [kokoko3k/xt7-player-mpv#1]
There is a way to specify the icon name to use the theme set on the desktop?

**Comment by kokoko3k** [comment]
Most of the icons are from the "stock" one, it means they are picked from the icon desktop theme.
Some are hadcoded, because i didn't find something appropriate.
Is there some icon in particular you would like to replace? I'll consider adding that option in the future.
Anyway, by now, you can manually change the icon files prior to compile xt7 by just replacing the files in the project directory.

**Comment by kokoko3k** [comment]
I replaced some icons with the ones from the system theme.
Some hardcoded icons remains, unfortunately, either because they are not defined by any freedesktop standard or because gambas stock does not provide one.
Let me know if it is ok for you.

**Comment by kokoko3k** [comment]
No answer in more than 2 months, closing.
