### ISSUE TITLE
Video plays in a separate mpv window on Wayland session of KDE Plasma desktop environment

### ISSUE THREAD

**Issue by glaubersm** [kokoko3k/xt7-player-mpv#32]
Steps to reproduce:
1. use Wayland session of KDE Plasma
2. play a video with xt7-player-mpv

Result: the video plays in a separate mpv window

Expected: the video plays inside xt7-player-mpv window

xt7-player-mpv: 0.33.3162

System.fullversion: 3.17.0

System.Architecture: x86_64

mpv: 
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0

**Comment by kokoko3k** [comment]
Hello,
I'm still on x11, but I verified the bug.

The workaround is to set:
```GB_GUI_PLATFORM=x11```
before starting xt7, example:
```> GB_GUI_PLATFORM=x11 xt7-player-mpv```

If you don't mind starting all of the gambas applications under XWayland, then you could set it somewhere system-wide (/etc/environment comes to mind)
This will force gambas to use x11 (Xwayland) instead of wayland.
Also double check that under **chains->Video Driver, gpu** is selected and **gpu context is set to x11egl.**

Unfortunately xt7 will never support wayland, because mpv does not support the way xt7 embeds his window under the main app; so till i find a better way to start xt7 under X without user intervention, this is my best advice.

Please leave this open.

**Comment by glaubersm** [comment]
> Unfortunately xt7 will never support wayland, because mpv does not support the way xt7 embeds his window under the main app;

have you reported this issue to mpv developers?

**Comment by kokoko3k** [comment]
Discussed long time ago:
https://github.com/mpv-player/mpv/issues/1242
But seems more like a Wayland feature/limitation.


Il giorno gio 31 mar 2022 alle ore 17:49 Strangiato <
***@***.***> ha scritto:

**Comment by kokoko3k** [comment]
Since there is not (yet?) a way to force the gui components to use X11 (Xwayland), in the latest commits and release 0.34.3170, the provided .desktop file will exec:
env GB_GUI_PLATFORM=x11 xt7-player-mpv.gambas

The Arch PKGBUILD has also been updated to do so.
Plus, xt7 will check the desktop environment on application startup displaying a warning if running under wayland.

As soon as gambas will provide a way to automate better the process, i will follow.

**Comment by glaubersm** [comment]
Currently I have xt7-player-mpv 0.34.3172-2 installed on Arch Linux, but this bug persists despite xt7-player-mpv is running on Xwayland.

**Comment by kokoko3k** [comment]
> Currently I have xt7-player-mpv 0.34.3172-2 installed on Arch Linux, but this bug persists despite xt7-player-mpv is running on Xwayland.

Works for me.

Please start xt7-player and while playing a video, provide the output of:
1) ```for p in `pidof gbr3` ; do strings /proc/$p/environ |grep 'xt7\|GB_GUI_PLATFORM'; done```

2) ```ps -ef|grep mpv|grep Xt7Input```

3) ```grep . /usr/share/applications/xt7*|grep GB ; grep . /usr/local/share/applications/xt7*|grep GB```

**Comment by glaubersm** [comment]
Here are the requested outputs:

1. ```GB_GUI_PLATFORM=x11```

2. stalker     2335    1142 57 13:43 ?        00:00:10 mpv --config=no --load-scripts=no --osc=no --dvbin-file=/home/stalker/.config/mpv/channels.conf.ter --wid=18874569 --cursor-autohide=no --cursor-autohide-fs-only=no --audio-display=no --input-cursor=no --input-vo-keyboard=no --cache=yes --cache-secs=3600 --demuxer-max-bytes=26214400 --af-add=@label_scaletempo:scaletempo --volume-max=100 --ad-lavc-ac3drc=1.0 --audio-channels=2 --audio-pitch-correction=yes --dvbin-card=1 --dvbin-timeout=10 --demuxer-lavf-probesize=512000 --sub-forced-only=yes --sub-bold=yes --sub-font=Bitstream Vera Sans --sub-font-size=24 --sub-border-size=1 --sub-border-color=#FF000000 --sub-shadow-offset=1 --sub-shadow-color=#FF000000 --osd-bold=yes --osd-font=Bitstream Vera Sans --osd-font-size=22 --osd-border-size=1 --osd-border-color=#FF000000 --osd-shadow-offset=1 --osd-shadow-color=#BF000000 --sub-auto=exact --sub-codepage=auto --alang=en,eng --slang=en,eng --vlang=en,eng --volume=12 --script=/tmp/gambas.1003/1142/killer.lua --input-ipc-server=/home/stalker/.config/gambas3/xt7-Player-mpv/.InputPipes/Xt7Input-4859 --msg-color=no --msg-level=all=v,cplayer=status,dvdnav=no,disc=no --term-status-msg=MPV_PLAY_IS_FULLY_INITIALIZED --force-seekable=yes /home/stalker/Vídeos/VID_20200804_104830930.mp4
```

3. ```Exec=env GB_GUI_PLATFORM=x11 xt7-player-mpv
grep: /usr/local/share/applications/xt7*: No such file or directory
```

**Comment by kokoko3k** [comment]
That's odd.
What if you force/select the "gpu" video output driver?

-EDIT-
Yeah, that seems to be it.
without any specified driver, mpv defaults to gpu one, but xt7 won't pass the needed options to it.
If you confirm that works for you, i'll leave this open and in the next release i will simply switch the checkbox driver on and to "gpu"

**Comment by glaubersm** [comment]
Can confirm that selecting "gpu' video output driver fixes the bug.
